/**
 * Regenerates rottenCherryPaths.ts from a font file.
 *
 * Run once, offline — this is a dev-time tool, not a runtime dependency.
 * The component ships static SVG path data so it never has to load or
 * parse a font in the browser.
 *
 * Usage:
 *   npm install opentype.js
 *   node generate-paths.js /path/to/RougeScript-Regular.ttf "Rotten Cherry"
 *
 * Rouge Script (the default pick) can be grabbed from the Google Fonts
 * GitHub mirror:
 *   https://github.com/google/fonts/raw/main/ofl/rougescript/RougeScript-Regular.ttf
 * (SIL Open Font License — see the OFL.txt next to it in that repo.)
 */

const opentype = require('opentype.js');
const fs = require('fs');
const path = require('path');

const [, , fontPathArg, textArg] = process.argv;

if (!fontPathArg) {
  console.error('Usage: node generate-paths.js <font.ttf> ["Text To Draw"]');
  process.exit(1);
}

const FONT_PATH = fontPathArg;
const TEXT = textArg || 'Rotten Cherry';
const FONT_SIZE = 120; // arbitrary; only relative proportions matter, viewBox adapts

// opentype.js's built-in Path#toPathData() has a serialization bug that
// occasionally emits a literal "NaN" for otherwise well-formed commands.
// Serializing the command list ourselves sidesteps it entirely.
function serializePath(openTypePath, decimals = 2) {
  const round = (v) => {
    const r = Number(v.toFixed(decimals));
    return Object.is(r, -0) ? 0 : r;
  };
  return openTypePath.commands
    .map((c) => {
      switch (c.type) {
        case 'M':
          return `M${round(c.x)} ${round(c.y)}`;
        case 'L':
          return `L${round(c.x)} ${round(c.y)}`;
        case 'C':
          return `C${round(c.x1)} ${round(c.y1)} ${round(c.x2)} ${round(c.y2)} ${round(c.x)} ${round(c.y)}`;
        case 'Q':
          return `Q${round(c.x1)} ${round(c.y1)} ${round(c.x)} ${round(c.y)}`;
        case 'Z':
          return 'Z';
        default:
          return '';
      }
    })
    .join('');
}

const buffer = fs.readFileSync(FONT_PATH);
const arrayBuffer = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
const font = opentype.parse(arrayBuffer);

const glyphs = [];
let x = 0;
const y = FONT_SIZE;
const scale = FONT_SIZE / font.unitsPerEm;

for (const char of TEXT) {
  const glyph = font.charToGlyph(char);
  const glyphPath = glyph.getPath(x, y, FONT_SIZE);
  const d = serializePath(glyphPath);
  if (char !== ' ' && d) {
    glyphs.push({ char, d });
  }
  x += glyph.advanceWidth * scale;
}

const fullPath = font.getPath(TEXT, 0, y, FONT_SIZE);
const bbox = fullPath.getBoundingBox();

const output = `/**
 * Pre-computed SVG glyph outlines for the "${TEXT}" wordmark.
 * Generated by generator/generate-paths.js from ${path.basename(FONT_PATH)} — do not hand-edit.
 */

export interface GlyphPath {
  char: string;
  d: string;
}

export const LOGO_GLYPHS: GlyphPath[] = ${JSON.stringify(glyphs, null, 2)};

export const LOGO_BBOX = ${JSON.stringify({ x1: bbox.x1, y1: bbox.y1, x2: bbox.x2, y2: bbox.y2 })};
`;

const outPath = path.join(__dirname, '..', 'rottenCherryPaths.ts');
fs.writeFileSync(outPath, output);
console.log(`Wrote ${glyphs.length} glyphs to ${outPath}`);
